name: CI
on:
  push:
    branches: [$default-branch]
  pull_request:
jobs:
  test:
    name: tests / ruby
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6.10', '3.0']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1.133.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          cache-version: 1

      - name: Run tests
        run: bundle exec rake
